import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ToastContainerCustom } from "@/components/feature/toast/ToastContainerCustom";
import { Header } from "@/components/layout/header/Header";
import { Footer } from "@/components/layout/Footer";

const pretendard = localFont({
  src: "../fonts/pretendard/PretendardVariable.woff2",
  display: "swap",
  weight: "100 900",
  variable: "--font-pretendard",
});
const gmarketsans = localFont({
  src: "../fonts/gmarketsans/GmarketSansBold.woff2",
  display: "swap",
  weight: "700",
  variable: "--font-gmarketsans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${pretendard.variable} ${gmarketsans.variable}`}>
      <body className={`${pretendard.variable} ${gmarketsans.variable}`}>
        <Header />
        <ToastContainerCustom />
        {children}
        <Footer />
      </body>
    </html>
  );
}
